trigger:
  - main
pool:
  vmImage: ubuntu-latest

variables:
  npm_config_cache: 'C:/hostedtoolcache/windows/.npm'

steps:
  - task: Cache@2
    inputs:
      key: 'package-lock.json'
      path: $(npm_config_cache)
    displayName: Cache NPM packages
  - task: Npm@1
    inputs:
      command: 'ci'
      workingDir: '$(npm_config_cache)'
  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: '$(npm_config_cache)'
  # - script: | 
  #     npm ci --cache $(npm_config_cache)
  #   displayName: NPM Install Dependencies
  #   # You need to set --cache explicitly, because the default location on POSIX systems is ~/.npm, which can't be accessed in a build agent as far as I know
  - script: |
      npm cache ls
      npm cache verify
    displayName: NPM Show cache
  - script: npm run lint
    displayName: Lint
  - script: npm run test:ci
    displayName: Unit Tests
  - script: npm run build
    displayName: Build
